FROM node:14 as builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY ./src/ /app/src/

COPY ./public/ /app/public/

RUN npm run build

FROM nginx:latest

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
