FROM golang:1.16-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY cmd/main.go ./

RUN go build -o main .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main /app/

EXPOSE 8080

CMD ["./main"]